"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { getEquipmentInspection } from "@/domain/equipment-inspection";

const STAGES = [
  { id:"preparation", no:"01", name:"Cane Preparation", short:"Cut & align", input:"Whole cane", output:"Prepared billets", x:-14 },
  { id:"shredding", no:"02", name:"Shredding", short:"Open fiber", input:"Billets", output:"Opened fiber", x:-10 },
  { id:"extraction", no:"03", name:"Juice Extraction", short:"Press & separate", input:"Shredded cane", output:"Juice + bagasse", x:-6 },
  { id:"clarification", no:"04", name:"Juice Clarification", short:"Settle solids", input:"Raw juice", output:"Clarified juice", x:-2 },
  { id:"evaporation", no:"05", name:"Evaporation", short:"Remove water", input:"Clarified juice", output:"Syrup", x:2 },
  { id:"crystallization", no:"06", name:"Crystallization", short:"Grow crystals", input:"Syrup", output:"Massecuite", x:6 },
  { id:"centrifugation", no:"07", name:"Centrifugation", short:"Separate phases", input:"Massecuite", output:"Sugar + molasses", x:10 },
  { id:"drying", no:"08", name:"Sugar Drying", short:"Reduce moisture", input:"Wet sugar", output:"Dry sugar", x:14 },
] as const;
type Stage = typeof STAGES[number];

const COLOR={bg:0x02080b,steel:0x829598,bright:0xc7d1cf,dark:0x111a1d,frame:0x2a3a3d,brass:0xb58b49,cane:0x9eaf5b,fiber:0xb9a56b,juice:0x8c6834,syrup:0x75471f,sugar:0xf1dca0,sludge:0x704c3d,cyan:0x6de1c5};
const M=(c:number,metal=.65,rough=.36)=>new THREE.MeshStandardMaterial({color:c,metalness:metal,roughness:rough});
function box(g:THREE.Object3D,s:[number,number,number],p:[number,number,number],m:THREE.Material){const o=new THREE.Mesh(new THREE.BoxGeometry(...s),m);o.position.set(...p);g.add(o);return o;}
function cyl(g:THREE.Object3D,r:number,h:number,p:[number,number,number],m:THREE.Material,rot?:[number,number,number]){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,28),m);o.position.set(...p);if(rot)o.rotation.set(...rot);g.add(o);return o;}
function tor(g:THREE.Object3D,r:number,t:number,p:[number,number,number],m:THREE.Material,rot?:[number,number,number]){const o=new THREE.Mesh(new THREE.TorusGeometry(r,t,10,32),m);o.position.set(...p);if(rot)o.rotation.set(...rot);g.add(o);return o;}
function pipe(g:THREE.Object3D,a:[number,number,number],b:[number,number,number],r:number,m:THREE.Material){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),d=bv.clone().sub(av);const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,d.length(),14),m);o.position.copy(av.clone().add(bv).multiplyScalar(.5));o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());g.add(o);return o;}
function supports(g:THREE.Object3D){const m=M(COLOR.frame,.8,.3);for(const x of[-1.5,1.5])for(const z of[-.72,.72])box(g,[.12,4.5,.12],[x,2.25,z],m);for(const y of[.15,4.35])box(g,[3.3,.12,1.56],[0,y,0],m);}

function machine(s:Stage){const g=new THREE.Group();g.userData.stageId=s.id;g.position.x=s.x;supports(g);const steel=M(COLOR.steel),bright=M(COLOR.bright),dark=M(COLOR.dark),brass=M(COLOR.brass,.9,.24);
  box(g,[3.5,.18,2.4],[0,-.05,0],dark);
  if(s.id==="preparation"){box(g,[2.8,.25,1.25],[0,1.05,0],dark);for(let i=-6;i<=6;i++)box(g,[.38,.16,1.05],[i*.22,1.32,0],M(COLOR.cane,.1,.72));cyl(g,.82,.18,[0,2.75,0],brass,[Math.PI/2,0,0]);for(let i=0;i<8;i++){const b=box(g,[.7,.08,.1],[.28,2.75,0],bright);b.rotation.z=i*Math.PI/4;}}
  if(s.id==="shredding"){box(g,[2.7,2.2,1.55],[0,2.05,0],dark);for(let i=-2;i<=2;i++){const r=cyl(g,.24,1.35,[i*.43,2.05,0],brass,[Math.PI/2,0,0]);r.rotation.z=.3;}box(g,[1,.4,1],[1.8,1.25,0],M(COLOR.fiber,.1,.8));}
  if(s.id==="extraction"){box(g,[3.1,2.5,1.7],[0,2.05,0],dark);for(let i=-1;i<=1;i++)cyl(g,.62,1.65,[i*.78,2.15,0],bright,[Math.PI/2,0,0]);box(g,[2.75,.3,1.45],[0,.75,0],M(COLOR.juice,.15,.6));box(g,[1.1,.8,1.1],[1.9,1.35,0],M(COLOR.fiber,.1,.75));}
  if(s.id==="clarification"){const glass=new THREE.MeshPhysicalMaterial({color:0x72b8bd,transparent:true,opacity:.42,transmission:.35,roughness:.18});cyl(g,1.3,3.25,[0,2.15,0],glass);cyl(g,1.08,.7,[0,1.25,0],M(COLOR.juice,.1,.6));cyl(g,1.08,.4,[0,.78,0],M(COLOR.sludge,.1,.7));cyl(g,.1,3,[0,2.2,0],brass);tor(g,.85,.07,[0,1.2,0],brass);}
  if(s.id==="evaporation"){for(let i=-1;i<=1;i++){cyl(g,.88,2.55,[i*1.05,2.1,0],steel);cyl(g,.7,.3,[i*1.05,1.02,0],M(COLOR.syrup,.1,.6));tor(g,.88,.08,[i*1.05,1.05,0],brass);}}
  if(s.id==="crystallization"){cyl(g,1.3,3,[0,2.05,0],steel);cyl(g,1.08,.65,[0,1.02,0],M(COLOR.syrup,.1,.55));cyl(g,.1,2.8,[0,2.1,0],brass);for(let i=0;i<18;i++)box(g,[.08,.08,.08],[Math.sin(i*2.2)*.8,1.15+(i%3)*.12,Math.cos(i*1.7)*.8],M(COLOR.sugar,.05,.35));}
  if(s.id==="centrifugation"){cyl(g,1.35,2.6,[0,2,0],dark);cyl(g,1.08,1.8,[0,2,0],brass);tor(g,1.08,.08,[0,2.85,0],bright);for(let i=0;i<18;i++)box(g,[.07,.07,.22],[Math.sin(i*2.2)*.9,1.65+(i%4)*.12,Math.cos(i*2.2)*.9],M(COLOR.sugar,.05,.35));}
  if(s.id==="drying"){cyl(g,1.05,2.9,[0,2,0],steel,[0,0,Math.PI/2]);for(let i=-1;i<=1;i++)tor(g,1.08,.1,[i*.85,2,0],brass,[0,Math.PI/2,0]);box(g,[1.9,.3,.85],[0,1.35,0],M(COLOR.sugar,.05,.35));}
  box(g,[.65,.65,.65],[-1.35,.48,.92],dark);return g;
}

function inspection(s:Stage){const g=new THREE.Group();const steel=M(COLOR.steel),bright=M(COLOR.bright),brass=M(COLOR.brass,.9,.24),sugar=M(COLOR.sugar,.05,.35),fiber=M(COLOR.fiber,.1,.75);supports(g);box(g,[6,.18,3.8],[0,-.1,0],M(COLOR.dark,.7,.5));
  if(s.id==="preparation"){box(g,[1.4,.5,2.4],[-2,1,0],M(COLOR.cane,.1,.7));cyl(g,1,.22,[0,2.2,0],brass,[Math.PI/2,0,0]);box(g,[1.6,.35,1.8],[2,.9,0],M(COLOR.cane,.1,.7));}
  if(s.id==="shredding"){box(g,[4,.7,2],[0,.8,0],fiber);for(let i=-1;i<=1;i++)cyl(g,.46,2.4,[i*1.05,2.1,0],brass,[Math.PI/2,0,0]);}
  if(s.id==="extraction"){for(let i=-1;i<=1;i++)cyl(g,.72,3.6,[i*1.05,2.1,0],steel,[Math.PI/2,0,0]);box(g,[5.2,.45,2.7],[0,.45,0],M(COLOR.juice,.15,.6));pipe(g,[-2.7,3.5,0],[2.7,3.5,0],.13,fiber);}
  if(s.id==="clarification"){cyl(g,1.75,3.2,[0,1.9,0],M(COLOR.juice,.1,.6));cyl(g,1.55,.45,[0,.45,0],M(COLOR.sludge,.1,.7));tor(g,1.3,.09,[0,1.5,0],brass);}
  if(s.id==="evaporation"){for(let i=-1;i<=1;i++){cyl(g,.82,3.2,[i*1.35,1.9,0],steel);cyl(g,.68,.5,[i*1.35,.75,0],M(COLOR.syrup,.1,.55));}}
  if(s.id==="crystallization"){cyl(g,1.9,3.5,[0,1.8,0],steel);cyl(g,1.65,.9,[0,.65,0],M(COLOR.syrup,.1,.5));for(let i=0;i<34;i++)box(g,[.07,.07,.07],[Math.sin(i*3.1)*1.4,.9+(i%5)*.12,Math.cos(i*2.2)*1.4],sugar);}
  if(s.id==="centrifugation"){cyl(g,1.75,2.7,[0,1.8,0],brass);for(let i=0;i<25;i++)box(g,[.08,.08,.25],[Math.sin(i*2.1)*1.5,1.3+(i%5)*.12,Math.cos(i*2.1)*1.5],sugar);}
  if(s.id==="drying"){cyl(g,1.45,4.5,[0,1.8,0],steel,[0,0,Math.PI/2]);box(g,[3.2,.4,1.2],[0,.85,0],sugar);pipe(g,[-2.8,3.4,0],[2.8,3.4,0],.16,bright);}
  return g;
}

export function ImmersiveSugarPlant(){
 const host=useRef<HTMLDivElement>(null);const sceneRef=useRef<THREE.Scene|null>(null);const camRef=useRef<THREE.PerspectiveCamera|null>(null);const controlsRef=useRef<OrbitControls|null>(null);const overviewRef=useRef<THREE.Group|null>(null);const insideRef=useRef<THREE.Group|null>(null);const targetPos=useRef(new THREE.Vector3());const targetLook=useRef(new THREE.Vector3());const moving=useRef(false);const [selectedId,setSelectedId]=useState<string|null>(null);const [inside,setInside]=useState(false);const selected=STAGES.find(s=>s.id===selectedId)||null;const index=selected?STAGES.findIndex(s=>s.id===selected.id):-1;const def=selected?getEquipmentInspection(selected.id):undefined;
 const focus=(s:Stage,enter=false)=>{const c=camRef.current;if(!c)return;moving.current=true;const x=s.x+(enter?0:0);targetPos.current.set(x,enter?3.1:5.4,enter?7.2:9.5);targetLook.current.set(x,enter?1.2:1.8,0);};
 useEffect(()=>{if(!host.current)return;const el=host.current;const scene=new THREE.Scene();scene.background=new THREE.Color(COLOR.bg);scene.fog=new THREE.Fog(COLOR.bg,24,62);sceneRef.current=scene;const camera=new THREE.PerspectiveCamera(42,el.clientWidth/el.clientHeight,.1,100);camera.position.set(0,7.5,28);camRef.current=camera;const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=4;controls.maxDistance=34;controls.maxPolarAngle=Math.PI*.49;controlsRef.current=controls;scene.add(new THREE.HemisphereLight(0xd8fff8,0x071014,2.1));const key=new THREE.DirectionalLight(0xffffff,3.5);key.position.set(5,12,10);scene.add(key);const glow=new THREE.PointLight(COLOR.cyan,12,28);glow.position.set(0,7,4);scene.add(glow);const floor=new THREE.Mesh(new THREE.PlaneGeometry(72,30),M(0x081114,.35,.75));floor.rotation.x=-Math.PI/2;scene.add(floor);const ov=new THREE.Group();overviewRef.current=ov;STAGES.forEach(s=>ov.add(machine(s)));scene.add(ov);
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),down=new THREE.Vector2();const onDown=(e:PointerEvent)=>down.set(e.clientX,e.clientY);const onUp=(e:PointerEvent)=>{if(moving.current||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)return;const q=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-q.left)/q.width)*2-1;pointer.y=-((e.clientY-q.top)/q.height)*2+1;ray.setFromCamera(pointer,camera);const root=insideRef.current||ov;const hit=ray.intersectObjects(root.children,true)[0]?.object;let node:THREE.Object3D|null=hit||null;while(node&&!node.userData.stageId)node=node.parent;if(node?.userData.stageId){setSelectedId(node.userData.stageId);const s=STAGES.find(v=>v.id===node!.userData.stageId);if(s)focus(s,false);}};renderer.domElement.addEventListener("pointerdown",onDown);renderer.domElement.addEventListener("pointerup",onUp);
 let raf=0;const tick=()=>{raf=requestAnimationFrame(tick);if(moving.current){camera.position.lerp(targetPos.current,.075);controls.target.lerp(targetLook.current,.075);if(camera.position.distanceTo(targetPos.current)<.035&&controls.target.distanceTo(targetLook.current)<.035){camera.position.copy(targetPos.current);controls.target.copy(targetLook.current);moving.current=false;}}controls.update();renderer.render(scene,camera);};tick();const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};const ro=new ResizeObserver(resize);ro.observe(el);return()=>{cancelAnimationFrame(raf);ro.disconnect();renderer.domElement.removeEventListener("pointerdown",onDown);renderer.domElement.removeEventListener("pointerup",onUp);controls.dispose();renderer.dispose();renderer.domElement.remove();};},[]);
 useEffect(()=>{const ov=overviewRef.current;if(!ov)return;if(inside){ov.visible=false;if(insideRef.current){insideRef.current.removeFromParent();insideRef.current=null;}if(selected){const g=inspection(selected);g.position.set(selected.x,0,0);insideRef.current=g;sceneRef.current?.add(g);focus(selected,true);}}else{ov.visible=true;if(insideRef.current){insideRef.current.removeFromParent();insideRef.current=null;}if(selected)focus(selected,false);}},[inside]);
 const enter=()=>{if(selected)setInside(true)};const back=()=>setInside(false);const selectStage=(s:Stage)=>{setSelectedId(s.id);if(!inside)focus(s,false)};
 return <div style={{position:"relative",height:"680px",border:"1px solid rgba(157,202,201,.14)",borderRadius:24,overflow:"hidden",background:"#02080b",boxShadow:"0 30px 80px rgba(0,0,0,.45)"}}>
   <div ref={host} style={{position:"absolute",inset:0}} />
   <div style={{position:"absolute",left:18,top:18,zIndex:5,pointerEvents:"none",background:"rgba(2,10,12,.76)",border:"1px solid rgba(157,202,201,.13)",borderRadius:14,padding:"11px 13px",backdropFilter:"blur(10px)"}}><div style={{fontSize:9,letterSpacing:2,color:"#70d0bd",fontWeight:800}}>{inside?"CUTAWAY INSPECTION":"PRODUCTION FLOOR"}</div><div style={{fontSize:15,fontWeight:750,marginTop:5}}>{inside&&selected?selected.name:"Sugarcane → Sugar"}</div></div>
   {selected&&!inside&&<div style={{position:"absolute",right:18,top:18,width:280,zIndex:5,padding:18,borderRadius:16,border:"1px solid rgba(157,202,201,.18)",background:"rgba(3,13,16,.86)",backdropFilter:"blur(14px)"}}><div style={{fontSize:9,color:"#70d0bd",fontWeight:800,letterSpacing:1.8}}>{selected.no} · SELECTED UNIT</div><div style={{fontSize:20,fontWeight:800,marginTop:7}}>{selected.name}</div><div style={{fontSize:11,color:"#9ddbd0",marginTop:5}}>{selected.short}</div><div style={{fontSize:10,color:"rgba(230,242,240,.55)",lineHeight:1.6,marginTop:12}}>IN · {selected.input}<br/>OUT · {selected.output}</div>{def&&<div style={{fontSize:9,color:"rgba(230,242,240,.45)",marginTop:9}}>{def.components.length} inspectable components · {def.flows.length} material flow{def.flows.length===1?"":"s"}</div>}<button onClick={enter} style={{width:"100%",marginTop:14,padding:"11px 12px",border:0,borderRadius:9,background:"#70d0bd",color:"#061012",fontWeight:850,cursor:"pointer"}}>ENTER CUTAWAY</button></div>}
   {inside&&selected&&<button onClick={back} style={{position:"absolute",right:18,top:18,zIndex:6,padding:"10px 13px",border:"1px solid rgba(157,202,201,.2)",borderRadius:9,background:"rgba(3,13,16,.86)",color:"#e9f4f2",fontWeight:750,cursor:"pointer"}}>← RETURN TO FACTORY</button>}
   {!inside&&<div style={{position:"absolute",left:18,right:18,bottom:18,zIndex:5,display:"flex",gap:7,overflowX:"auto",padding:"8px 0"}}>{STAGES.map(s=><button key={s.id} onClick={()=>selectStage(s)} style={{minWidth:122,padding:"9px 10px",borderRadius:9,border:`1px solid ${selectedId===s.id?"rgba(112,208,189,.65)":"rgba(157,202,201,.13)"}`,background:selectedId===s.id?"rgba(39,103,94,.72)":"rgba(3,13,16,.76)",color:"#e9f4f2",textAlign:"left",cursor:"pointer"}}><span style={{fontSize:8,color:"#70d0bd",fontWeight:800}}>{s.no}</span><div style={{fontSize:10,fontWeight:750,marginTop:4}}>{s.name}</div></button>)}</div>}
   {inside&&<div style={{position:"absolute",left:18,right:18,bottom:18,zIndex:5,display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 12px",borderRadius:11,border:"1px solid rgba(157,202,201,.12)",background:"rgba(3,13,16,.72)",fontSize:10}}><span style={{color:"rgba(230,242,240,.55)"}}>Inspect the transformation inside this unit</span><span style={{color:"#70d0bd",fontWeight:800}}>{selected?.no} / 08</span></div>}
 </div>;
}
