"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { getEquipmentInspection } from "@/domain/equipment-inspection";

const STAGES = [
  { id: "preparation", no: "01", name: "Cane Preparation", short: "Cut & align", input: "Whole cane", output: "Prepared billets", x: -14 },
  { id: "shredding", no: "02", name: "Shredding", short: "Open fiber", input: "Billets", output: "Opened fiber", x: -10 },
  { id: "extraction", no: "03", name: "Juice Extraction", short: "Press & separate", input: "Shredded cane", output: "Juice + bagasse", x: -6 },
  { id: "clarification", no: "04", name: "Juice Clarification", short: "Settle solids", input: "Raw juice", output: "Clarified juice", x: -2 },
  { id: "evaporation", no: "05", name: "Evaporation", short: "Remove water", input: "Clarified juice", output: "Syrup", x: 2 },
  { id: "crystallization", no: "06", name: "Crystallization", short: "Grow crystals", input: "Syrup", output: "Massecuite", x: 6 },
  { id: "centrifugation", no: "07", name: "Centrifugation", short: "Separate phases", input: "Massecuite", output: "Sugar + molasses", x: 10 },
  { id: "drying", no: "08", name: "Sugar Drying", short: "Reduce moisture", input: "Wet sugar", output: "Dry sugar", x: 14 },
] as const;
type Stage = (typeof STAGES)[number];

const C = { bg: 0x02080b, steel: 0x829598, bright: 0xc7d1cf, dark: 0x111a1d, frame: 0x2a3a3d, brass: 0xb58b49, cane: 0x9eaf5b, fiber: 0xb9a56b, juice: 0x8c6834, syrup: 0x75471f, sugar: 0xf1dca0, sludge: 0x704c3d, cyan: 0x6de1c5 };
const mat = (color: number, metalness = 0.65, roughness = 0.36) => new THREE.MeshStandardMaterial({ color, metalness, roughness });
function box(g: THREE.Object3D, size: [number, number, number], pos: [number, number, number], material: THREE.Material) { const o = new THREE.Mesh(new THREE.BoxGeometry(...size), material); o.position.set(...pos); g.add(o); return o; }
function cyl(g: THREE.Object3D, radius: number, height: number, pos: [number, number, number], material: THREE.Material, rotation?: [number, number, number]) { const o = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius, height, 28), material); o.position.set(...pos); if (rotation) o.rotation.set(...rotation); g.add(o); return o; }
function torus(g: THREE.Object3D, radius: number, tube: number, pos: [number, number, number], material: THREE.Material, rotation?: [number, number, number]) { const o = new THREE.Mesh(new THREE.TorusGeometry(radius, tube, 10, 32), material); o.position.set(...pos); if (rotation) o.rotation.set(...rotation); g.add(o); return o; }
function pipe(g: THREE.Object3D, a: [number, number, number], b: [number, number, number], radius: number, material: THREE.Material) { const av = new THREE.Vector3(...a), bv = new THREE.Vector3(...b), d = bv.clone().sub(av); const o = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius, d.length(), 14), material); o.position.copy(av.clone().add(bv).multiplyScalar(0.5)); o.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), d.normalize()); g.add(o); return o; }
function supports(g: THREE.Object3D) { const m = mat(C.frame, 0.8, 0.3); for (const x of [-1.5, 1.5]) for (const z of [-0.72, 0.72]) box(g, [0.12, 4.5, 0.12], [x, 2.25, z], m); for (const y of [0.15, 4.35]) box(g, [3.3, 0.12, 1.56], [0, y, 0], m); }

function machine(s: Stage) {
  const g = new THREE.Group(); g.userData.stageId = s.id; g.position.x = s.x; supports(g);
  const steel = mat(C.steel), bright = mat(C.bright), dark = mat(C.dark), brass = mat(C.brass, 0.9, 0.24); box(g, [3.5, 0.18, 2.4], [0, -0.05, 0], dark);
  if (s.id === "preparation") { box(g, [2.8, 0.25, 1.25], [0, 1.05, 0], dark); for (let i = -6; i <= 6; i++) box(g, [0.38, 0.16, 1.05], [i * 0.22, 1.32, 0], mat(C.cane, 0.1, 0.72)); cyl(g, 0.82, 0.18, [0, 2.75, 0], brass, [Math.PI / 2, 0, 0]); for (let i = 0; i < 8; i++) { const b = box(g, [0.7, 0.08, 0.1], [0.28, 2.75, 0], bright); b.rotation.z = i * Math.PI / 4; } }
  else if (s.id === "shredding") { box(g, [2.7, 2.2, 1.55], [0, 2.05, 0], dark); for (let i = -2; i <= 2; i++) { const r = cyl(g, 0.24, 1.35, [i * 0.43, 2.05, 0], brass, [Math.PI / 2, 0, 0]); r.rotation.z = 0.3; } box(g, [1, 0.4, 1], [1.8, 1.25, 0], mat(C.fiber, 0.1, 0.8)); }
  else if (s.id === "extraction") { box(g, [3.1, 2.5, 1.7], [0, 2.05, 0], dark); for (let i = -1; i <= 1; i++) cyl(g, 0.62, 1.65, [i * 0.78, 2.15, 0], bright, [Math.PI / 2, 0, 0]); box(g, [2.75, 0.3, 1.45], [0, 0.75, 0], mat(C.juice, 0.15, 0.6)); box(g, [1.1, 0.8, 1.1], [1.9, 1.35, 0], mat(C.fiber, 0.1, 0.75)); }
  else if (s.id === "clarification") { const glass = new THREE.MeshPhysicalMaterial({ color: 0x72b8bd, transparent: true, opacity: 0.42, transmission: 0.35, roughness: 0.18 }); cyl(g, 1.3, 3.25, [0, 2.15, 0], glass); cyl(g, 1.08, 0.7, [0, 1.25, 0], mat(C.juice, 0.1, 0.6)); cyl(g, 1.08, 0.4, [0, 0.78, 0], mat(C.sludge, 0.1, 0.7)); cyl(g, 0.1, 3, [0, 2.2, 0], brass); torus(g, 0.85, 0.07, [0, 1.2, 0], brass); }
  else if (s.id === "evaporation") { for (let i = -1; i <= 1; i++) { cyl(g, 0.88, 2.55, [i * 1.05, 2.1, 0], steel); cyl(g, 0.7, 0.3, [i * 1.05, 1.02, 0], mat(C.syrup, 0.1, 0.6)); torus(g, 0.88, 0.08, [i * 1.05, 1.05, 0], brass); } }
  else if (s.id === "crystallization") { cyl(g, 1.3, 3, [0, 2.05, 0], steel); cyl(g, 1.08, 0.65, [0, 1.02, 0], mat(C.syrup, 0.1, 0.55)); cyl(g, 0.1, 2.8, [0, 2.1, 0], brass); for (let i = 0; i < 18; i++) box(g, [0.08, 0.08, 0.08], [Math.sin(i * 2.2) * 0.8, 1.15 + (i % 3) * 0.12, Math.cos(i * 1.7) * 0.8], mat(C.sugar, 0.05, 0.35)); }
  else if (s.id === "centrifugation") { cyl(g, 1.35, 2.6, [0, 2, 0], dark); cyl(g, 1.08, 1.8, [0, 2, 0], brass); torus(g, 1.08, 0.08, [0, 2.85, 0], bright); for (let i = 0; i < 18; i++) box(g, [0.07, 0.07, 0.22], [Math.sin(i * 2.2) * 0.9, 1.65 + (i % 4) * 0.12, Math.cos(i * 2.2) * 0.9], mat(C.sugar, 0.05, 0.35)); }
  else if (s.id === "drying") { cyl(g, 1.05, 2.9, [0, 2, 0], steel, [0, 0, Math.PI / 2]); for (let i = -1; i <= 1; i++) torus(g, 1.08, 0.1, [i * 0.85, 2, 0], brass, [0, Math.PI / 2, 0]); box(g, [1.9, 0.3, 0.85], [0, 1.35, 0], mat(C.sugar, 0.05, 0.35)); }
  return g;
}

function inspection(s: Stage) {
  const g = new THREE.Group(); const steel = mat(C.steel), bright = mat(C.bright), brass = mat(C.brass, 0.9, 0.24), sugar = mat(C.sugar, 0.05, 0.35), fiber = mat(C.fiber, 0.1, 0.75); supports(g); box(g, [6, 0.18, 3.8], [0, -0.1, 0], mat(C.dark, 0.7, 0.5));
  if (s.id === "preparation") { box(g, [1.4, 0.5, 2.4], [-2, 1, 0], mat(C.cane, 0.1, 0.7)); cyl(g, 1, 0.22, [0, 2.2, 0], brass, [Math.PI / 2, 0, 0]); box(g, [1.6, 0.35, 1.8], [2, 0.9, 0], mat(C.cane, 0.1, 0.7)); }
  else if (s.id === "shredding") { box(g, [4, 0.7, 2], [0, 0.8, 0], fiber); for (let i = -1; i <= 1; i++) cyl(g, 0.46, 2.4, [i * 1.05, 2.1, 0], brass, [Math.PI / 2, 0, 0]); }
  else if (s.id === "extraction") { for (let i = -1; i <= 1; i++) cyl(g, 0.72, 3.6, [i * 1.05, 2.1, 0], steel, [Math.PI / 2, 0, 0]); box(g, [5.2, 0.45, 2.7], [0, 0.45, 0], mat(C.juice, 0.15, 0.6)); pipe(g, [-2.7, 3.5, 0], [2.7, 3.5, 0], 0.13, fiber); }
  else if (s.id === "clarification") { cyl(g, 1.75, 3.2, [0, 1.9, 0], mat(C.juice, 0.1, 0.6)); cyl(g, 1.55, 0.45, [0, 0.45, 0], mat(C.sludge, 0.1, 0.7)); torus(g, 1.3, 0.09, [0, 1.5, 0], brass); }
  else if (s.id === "evaporation") { for (let i = -1; i <= 1; i++) { cyl(g, 0.82, 3.2, [i * 1.35, 1.9, 0], steel); cyl(g, 0.68, 0.5, [i * 1.35, 0.75, 0], mat(C.syrup, 0.1, 0.55)); } }
  else if (s.id === "crystallization") { cyl(g, 1.9, 3.5, [0, 1.8, 0], steel); cyl(g, 1.65, 0.9, [0, 0.65, 0], mat(C.syrup, 0.1, 0.5)); for (let i = 0; i < 34; i++) box(g, [0.07, 0.07, 0.07], [Math.sin(i * 3.1) * 1.4, 0.9 + (i % 5) * 0.12, Math.cos(i * 2.2) * 1.4], sugar); }
  else if (s.id === "centrifugation") { cyl(g, 1.75, 2.7, [0, 1.8, 0], brass); for (let i = 0; i < 25; i++) box(g, [0.08, 0.08, 0.25], [Math.sin(i * 2.1) * 1.5, 1.3 + (i % 5) * 0.12, Math.cos(i * 2.1) * 1.5], sugar); }
  else if (s.id === "drying") { cyl(g, 1.45, 4.5, [0, 1.8, 0], steel, [0, 0, Math.PI / 2]); box(g, [3.2, 0.4, 1.2], [0, 0.85, 0], sugar); pipe(g, [-2.8, 3.4, 0], [2.8, 3.4, 0], 0.16, bright); }
  return g;
}

export function ImmersiveSugarPlant() {
  const host = useRef<HTMLDivElement>(null); const cameraRef = useRef<THREE.PerspectiveCamera | null>(null); const controlsRef = useRef<OrbitControls | null>(null); const overviewRef = useRef<THREE.Group | null>(null); const insideRef = useRef<THREE.Group | null>(null); const movingRef = useRef(false); const targetPosition = useRef(new THREE.Vector3()); const targetLook = useRef(new THREE.Vector3());
  const [selectedId, setSelectedId] = useState<string | null>(null); const [inside, setInside] = useState(false); const selected = useMemo(() => STAGES.find((s) => s.id === selectedId) ?? null, [selectedId]); const definition = selected ? getEquipmentInspection(selected.id) : undefined;
  const focusStage = (stage: Stage, enter = false) => { const camera = cameraRef.current, controls = controlsRef.current; if (!camera || !controls) return; movingRef.current = true; targetPosition.current.set(stage.x, enter ? 3.1 : 5.6, enter ? 7.2 : 10.5); targetLook.current.set(stage.x, enter ? 1.45 : 1.9, 0); controls.enabled = false; };

  useEffect(() => {
    const el = host.current; if (!el) return; const scene = new THREE.Scene(); scene.background = new THREE.Color(C.bg); scene.fog = new THREE.Fog(C.bg, 26, 68);
    const camera = new THREE.PerspectiveCamera(42, el.clientWidth / el.clientHeight, 0.1, 100); camera.position.set(0, 8, 30); camera.lookAt(0, 1.7, 0); cameraRef.current = camera;
    const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: "high-performance" }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); renderer.setSize(el.clientWidth, el.clientHeight); renderer.outputColorSpace = THREE.SRGBColorSpace; el.appendChild(renderer.domElement);
    const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.dampingFactor = 0.08; controls.minDistance = 5; controls.maxDistance = 36; controls.maxPolarAngle = Math.PI * 0.49; controls.target.set(0, 1.7, 0); controlsRef.current = controls;
    scene.add(new THREE.HemisphereLight(0xd8fff8, 0x071014, 2.1)); const key = new THREE.DirectionalLight(0xffffff, 3.5); key.position.set(5, 12, 10); scene.add(key); const glow = new THREE.PointLight(C.cyan, 12, 30); glow.position.set(0, 7, 4); scene.add(glow); const floor = new THREE.Mesh(new THREE.PlaneGeometry(72, 34), mat(0x081114, 0.35, 0.75)); floor.rotation.x = -Math.PI / 2; scene.add(floor);
    const overview = new THREE.Group(); overviewRef.current = overview; STAGES.forEach((stage) => overview.add(machine(stage))); scene.add(overview);
    const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); const down = new THREE.Vector2();
    const pointerDown = (event: PointerEvent) => down.set(event.clientX, event.clientY);
    const pointerUp = (event: PointerEvent) => { if (movingRef.current || Math.hypot(event.clientX - down.x, event.clientY - down.y) > 6) return; const rect = renderer.domElement.getBoundingClientRect(); pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1; pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1; raycaster.setFromCamera(pointer, camera); const root = insideRef.current ?? overview; const hit = raycaster.intersectObjects(root.children, true)[0]?.object; let node: THREE.Object3D | null = hit ?? null; while (node && !node.userData.stageId) node = node.parent; const stageId = node?.userData.stageId as string | undefined; if (stageId) { const stage = STAGES.find((item) => item.id === stageId); if (stage) { setSelectedId(stage.id); focusStage(stage); } } };
    renderer.domElement.addEventListener("pointerdown", pointerDown); renderer.domElement.addEventListener("pointerup", pointerUp);
    let frame = 0; const animate = () => { frame = requestAnimationFrame(animate); if (movingRef.current) { camera.position.lerp(targetPosition.current, 0.09); controls.target.lerp(targetLook.current, 0.09); if (camera.position.distanceTo(targetPosition.current) < 0.04 && controls.target.distanceTo(targetLook.current) < 0.04) { camera.position.copy(targetPosition.current); controls.target.copy(targetLook.current); movingRef.current = false; controls.enabled = true; } } controls.update(); renderer.render(scene, camera); }; animate();
    const resize = () => { camera.aspect = el.clientWidth / el.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(el.clientWidth, el.clientHeight); }; const observer = new ResizeObserver(resize); observer.observe(el);
    return () => { cancelAnimationFrame(frame); observer.disconnect(); renderer.domElement.removeEventListener("pointerdown", pointerDown); renderer.domElement.removeEventListener("pointerup", pointerUp); controls.dispose(); renderer.dispose(); if (renderer.domElement.parentElement === el) el.removeChild(renderer.domElement); };
  }, []);

  useEffect(() => { const overview = overviewRef.current; if (!overview) return; const scene = overview.parent; if (!scene) return; if (inside) { overview.visible = false; const current = selected ?? STAGES[0]; const group = inspection(current); group.userData.stageId = current.id; insideRef.current = group; scene.add(group); requestAnimationFrame(() => focusStage(current, true)); return () => { scene.remove(group); insideRef.current = null; overview.visible = true; }; } overview.visible = true; }, [inside, selected]);

  const selectStage = (stage: Stage) => { setSelectedId(stage.id); focusStage(stage); };
  const enter = () => { if (selected) setInside(true); };
  const exit = () => { setInside(false); const camera = cameraRef.current, controls = controlsRef.current; if (camera && controls) { movingRef.current = true; targetPosition.current.set(0, 8, 30); targetLook.current.set(0, 1.7, 0); controls.enabled = false; } };

  return <div style={{ position: "relative", width: "100%", height: "min(760px, 72vh)", minHeight: 620, overflow: "hidden", border: "1px solid rgba(150,220,205,.12)", borderRadius: 22, background: "#02080b" }}>
    <div ref={host} style={{ position: "absolute", inset: 0 }} />
    <div style={{ position: "absolute", inset: 0, pointerEvents: "none", background: "linear-gradient(90deg, rgba(2,8,11,.78), transparent 32%, transparent 68%, rgba(2,8,11,.45))" }} />
    <div style={{ position: "absolute", left: 22, top: 20, zIndex: 10, color: "#edf7f4", pointerEvents: "none" }}><div style={{ fontSize: 10, letterSpacing: 2.4, color: "#70d0bd", fontWeight: 800 }}>FOOD PROCESS LAB · SUGAR HOUSE</div><div style={{ fontSize: 25, fontWeight: 700, marginTop: 7 }}>{inside ? "Inside the process" : "Production floor"}</div><div style={{ fontSize: 11, color: "rgba(225,239,238,.55)", marginTop: 5 }}>{inside ? "Inspect the transformation inside this unit." : "Choose a unit to inspect the material transformation."}</div></div>
    {!inside && <div style={{ position: "absolute", left: 20, top: 118, zIndex: 20, width: 245, padding: 10, borderRadius: 16, background: "rgba(3,12,14,.88)", border: "1px solid rgba(150,220,205,.16)", backdropFilter: "blur(12px)" }}><div style={{ padding: "7px 9px 9px", color: "rgba(225,239,238,.42)", fontSize: 9, letterSpacing: 1.8 }}>PROCESS UNITS</div>{STAGES.map((stage) => { const active = stage.id === selectedId; return <button key={stage.id} onClick={() => selectStage(stage)} style={{ display: "block", width: "100%", textAlign: "left", cursor: "pointer", padding: "10px", marginBottom: 4, borderRadius: 10, border: active ? "1px solid rgba(112,208,189,.5)" : "1px solid transparent", background: active ? "rgba(61,147,132,.2)" : "transparent", color: active ? "#eaf9f5" : "rgba(225,239,238,.65)", fontSize: 11 }}><span style={{ color: "#70d0bd", marginRight: 9, fontSize: 9 }}>{stage.no}</span>{stage.name}<span style={{ display: "block", marginLeft: 25, marginTop: 3, color: "rgba(225,239,238,.35)", fontSize: 8 }}>{stage.short}</span></button>; })}</div>}
    {selected && !inside && <div style={{ position: "absolute", right: 20, bottom: 20, zIndex: 20, width: 300, padding: 18, borderRadius: 17, background: "rgba(3,12,14,.92)", border: "1px solid rgba(112,208,189,.24)", color: "#edf7f4" }}><div style={{ color: "#70d0bd", fontSize: 9, letterSpacing: 1.6 }}>UNIT {selected.no}</div><div style={{ fontSize: 20, fontWeight: 700, marginTop: 5 }}>{selected.name}</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 14 }}><div style={{ padding: 9, background: "rgba(255,255,255,.035)", borderRadius: 9 }}><div style={{ fontSize: 8, color: "rgba(225,239,238,.38)" }}>INPUT</div><div style={{ marginTop: 4, fontSize: 10 }}>{selected.input}</div></div><div style={{ padding: 9, background: "rgba(255,255,255,.035)", borderRadius: 9 }}><div style={{ fontSize: 8, color: "rgba(225,239,238,.38)" }}>OUTPUT</div><div style={{ marginTop: 4, fontSize: 10 }}>{selected.output}</div></div></div><button onClick={enter} style={{ width: "100%", marginTop: 13, padding: "11px 12px", border: 0, borderRadius: 10, background: "#70d0bd", color: "#03100e", fontWeight: 800, fontSize: 10, letterSpacing: 1.2, cursor: "pointer" }}>ENTER CUTAWAY →</button></div>}
    {inside && <div style={{ position: "absolute", right: 20, bottom: 20, zIndex: 20, width: 300, padding: 17, borderRadius: 17, background: "rgba(3,12,14,.92)", border: "1px solid rgba(112,208,189,.24)", color: "#edf7f4" }}><div style={{ color: "#70d0bd", fontSize: 9, letterSpacing: 1.6 }}>CUTAWAY · UNIT {selected?.no}</div><div style={{ fontSize: 19, fontWeight: 700, marginTop: 5 }}>{selected?.name}</div><div style={{ marginTop: 9, color: "rgba(225,239,238,.5)", fontSize: 10, lineHeight: 1.55 }}>{definition?.cutawayPurpose ?? "Inspect the internal transformation."}</div><button onClick={exit} style={{ width: "100%", marginTop: 13, padding: "11px 12px", border: "1px solid rgba(150,220,205,.25)", borderRadius: 10, background: "rgba(255,255,255,.04)", color: "#eaf8f4", fontWeight: 700, fontSize: 10, letterSpacing: 1, cursor: "pointer" }}>← RETURN TO FACTORY</button></div>}
    <div style={{ position: "absolute", right: 20, top: 20, zIndex: 10, padding: "7px 10px", border: "1px solid rgba(150,220,205,.16)", borderRadius: 999, background: "rgba(4,13,15,.65)", color: "#b8d9d2", fontSize: 9, letterSpacing: 1.4, pointerEvents: "none" }}>DRAG · ORBIT &nbsp; SCROLL · ZOOM</div>
  </div>;
}
